### PR TITLE
Add restore mode

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by ckaenzig** [comment]
Documentation for restore mode is missing.

**Comment by mcanevet** [comment]
@ckaenzig done

**Comment by ckaenzig** [comment]
@mcanevet okay. But one thing I might be missing. The parameter `--restore` can only be passed on a docker command line, right ? If so, that seems very limiting. It should be possible to restore to a rancher stack (i.e. creating a new postgresql container based on existing backups instead of an empty cluster).

**Comment by mcanevet** [comment]
@ckaenzig you can pass `--restore` in a `docker-compose.yml` using the `command` key in the hash

**Comment by mbornoz** [comment]
There are still 2 missing mutually exclusive **optional** options:

- PGHOARD_RECOVERY_TARGET_TIME (ISO Timestamp)
- PGHOARD_RECOVERY_TARGET_XID (Transaction ID)

**Comment by mcanevet** [comment]
@mbornoz I changed a little bit the logic. Now for using the restore mode, one just have to set `PGHOARD_RESTORE_SITE` and can optionally add any additional options to `pghoard_restore` using Docker's `command` (including `--recovery-target-time` or `--recovery-target-xid`).

**Comment by mcanevet** [comment]
@mbornoz major refactoring. Note: this will require changing the entrypoint to `/backup.sh` in https://github.com/camptocamp/rancher-template-postgres-cluster

**Pull request merged**
